### ISSUE TITLE
Data not Reset after session

### ISSUE THREAD

**Issue by vvarshad** [senthilnathan89/se23ft5ConfigMgmt#1]
The data is not reset to Null on completion of the session(i.e. After “Press here if finished” is clicked). Total cash held by the system(Show Total Cash Held) and the total coins respective to the cash held by the system(Collect Cash) should reset to null once the system maintainer collects the cash and ends the session.

**Comment by divakarsivashankar** [comment]
Analysed the technical details of the Bug and determined the workflow  to solve this bug.

**Comment by atmel21** [comment]
Way to do the continuous integration is decided.

**Comment by atmel21** [comment]
Defect fixing - Done
Time taken - 2 hours.

**Comment by Lavanya16** [comment]
Fix has been integrated and all the tests are passed.

**Comment by saisat93** [comment]
Reviewed the changes. Approved for release.

**Comment by senthilnathan89** [comment]
Released in R1.0.9

**Comment by vvarshad** [comment]
Accepted.
