### ISSUE TITLE
The denomination quantity and amount tally with the Total Cash Held and Total Coins To Collect.

### ISSUE THREAD

**Issue by vvarshad** [senthilnathan89/se23ft5ConfigMgmt#2]
The system is required to provide a display of cash amount available, by denomination for collection by the maintainer. This display  of amount  and quantity per denomination should tally with the Total cash held and its equivalent coins held by the system, for ready/easy checking by the maintainer.

**Comment by divakarsivashankar** [comment]
Enhancement is analysed for its technicality and the approach to implement it.

**Comment by divakarsivashankar** [comment]
Assigning to @ekhoenix since @atmel21  is busy with the defect.

**Comment by ekhoenix** [comment]
Analyzing the change request

**Comment by ekhoenix** [comment]
Defect fixing - Done
Time taken - 8 hours.

**Comment by Lavanya16** [comment]
Code has been integrated and all the test cases passed.

**Comment by saisat93** [comment]
Reviewed the changes. Approved for release.

**Comment by senthilnathan89** [comment]
Released in R1.0.9

**Comment by vvarshad** [comment]
Accepted.
